In [1]:
import numpy as np

In [2]:
import time

In [3]:
# 1. Array Creation
array_1d = np.array([10, 20, 30, 40, 50])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:

print("1D Array:", array_1d)
print("2D Array:\n", array_2d)

1D Array: [10 20 30 40 50]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [6]:
# 2. Indexing and Slicing
print("First element:", array_1d[0])
print("Slice (index 1 to 3):", array_1d[1:4])
print("2D element:", array_2d[1, 2])

First element: 10
Slice (index 1 to 3): [20 30 40]
2D element: 6


In [7]:
# 3. Mathematical Operations
print("Addition:", array_1d + 5)
print("Multiplication:", array_1d * 2)

Addition: [15 25 35 45 55]
Multiplication: [ 20  40  60  80 100]


In [8]:
# 4. Statistical Operations
print("Mean:", np.mean(array_1d))
print("Median:", np.median(array_1d))
print("Standard Deviation:", np.std(array_1d))
print("Sum:", np.sum(array_1d))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Sum: 150


In [9]:

# 5. Axis-wise Operations
print("Column Sum:", np.sum(array_2d, axis=0))
print("Row Sum:", np.sum(array_2d, axis=1))

Column Sum: [5 7 9]
Row Sum: [ 6 15]


In [10]:
# 6. Reshaping
reshaped = array_1d.reshape(5, 1)
print("Reshaped Array:\n", reshaped)

Reshaped Array:
 [[10]
 [20]
 [30]
 [40]
 [50]]


In [11]:

# 7. Broadcasting
broadcast_result = array_2d + np.array([10, 20, 30])
print("Broadcasting Result:\n", broadcast_result)

Broadcasting Result:
 [[11 22 33]
 [14 25 36]]


In [12]:

# 8. Save and Load NumPy Array
np.save("data_saved.npy", array_1d)
loaded_array = np.load("data_saved.npy")
print("Loaded Array:", loaded_array)

Loaded Array: [10 20 30 40 50]


In [13]:
# 9. Performance Comparison
size = 1000000

In [14]:
python_list = list(range(size))
numpy_array = np.arange(size)


In [15]:
start = time.time()
python_sum = sum(python_list)
end = time.time()
print("Python List Sum Time:", end - start)

Python List Sum Time: 0.021124601364135742


In [16]:
start = time.time()
numpy_sum = np.sum(numpy_array)
end = time.time()
print("NumPy Array Sum Time:", end - start)

NumPy Array Sum Time: 0.0013926029205322266
